fieldLayouts:
  e4b3a179-69e3-4420-9d48-08007ecc8016:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cefa3abb-1f5b-4053-8d85-bf29a2a4c28b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 228a5106-64d8-456d-8950-6617735b6a9e # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bc8422b-04a8-4752-9a5c-4d731a20654d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22551e37-4303-4127-9d5b-d5ae046c6f61 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91dd317e-73ce-450c-aad5-5991aefa4a0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 626d0ba5-a8a2-4731-be65-81ab1bd9073e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aaec7dbc-0bbb-4b12-9947-4b02335e61b7 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64b1fd89-cb94-42d4-9d46-046908a9955c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02f114bd-d885-4d9d-9d23-b33fc220000e # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d37d4cde-beec-4f98-b8c7-8ab36a8d1195
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e9843eb-00f5-4a5a-8841-362d367feadd # Social Share
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77a38516-54e4-49b9-9114-a95f1f28d978
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 9c9bad3e-e127-4e32-b6be-8aaed29e54f1
        userCondition: null
handle: stadiumsHome
hasTitleField: false
name: 'Stadiums Home'
section: 4b7d6748-f9e7-4f63-9d59-25f3f3fb8cfb # Stadiums Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
