defaultPlacement: end
fieldLayouts:
  9c4a589e-2f68-4f31-9f79-92380f559c33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 20e553a9-67be-4bf6-95ab-9473b47e1dad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f8641d9-b724-4273-9310-c2ffe0b4934c # Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3e121fe-1830-45da-b3db-474dc6cb8081
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21e49b52-1a6b-4710-b51a-99a7ecf35ef0
        userCondition: null
handle: teamColours
name: 'Team Colours'
siteSettings:
  4a316ab3-49ff-4925-aada-2e783ce740ae: # myfootballtour.co.uk
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 60cf5be8-0bc4-4e8b-b168-320d2b65ecb4
