columnSuffix: hyoukfai
contentColumnType: integer(6)
fieldGroup: 6c8c42c3-05c3-459d-8541-0e851ec675ac # Stadiums
handle: capacity
instructions: null
name: Capacity
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 100000
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
