columnSuffix: gkwuwvog
contentColumnType: integer(10)
fieldGroup: 6c8c42c3-05c3-459d-8541-0e851ec675ac # Stadiums
handle: closing
instructions: 'The year the stadium is scheduled to close (if applicable).'
name: Closing
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: 4
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
