columnSuffix: aszevyce
contentColumnType: string(255)
fieldGroup: 6c8c42c3-05c3-459d-8541-0e851ec675ac # Stadiums
handle: clubWebsite
instructions: null
name: 'Club website'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
