columnSuffix: null
contentColumnType: string
fieldGroup: 6c8c42c3-05c3-459d-8541-0e851ec675ac # Stadiums
handle: mainStadiumImage
instructions: 'The main image of the stadium which will be displayed on the stadiums page.'
name: 'Main stadium image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:1e16db7a-6624-4b1c-a710-26613a5064e9' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:1e16db7a-6624-4b1c-a710-26613a5064e9' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
