columnSuffix: grbxqszi
contentColumnType: text
fieldGroup: 6c8c42c3-05c3-459d-8541-0e851ec675ac # Stadiums
handle: team
instructions: 'The team that primarily plays its home games at the stadium.'
name: Team
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
