dateModified: 1724956435
elementSources:
  craft\elements\Category:
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:fbf6d79a-ab27-43a9-b11d-83e6aca93740' # Team Colours
      tableAttributes:
        - 'field:7f8641d9-b724-4273-9310-c2ffe0b4934c' # Colour
        - id
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:c00bb2ae-23ed-4ea3-9980-2bb84200e929' # Regions
      tableAttributes:
        - 'field:87ba3899-10a7-42c3-862f-eefec96e9753' # Map image
      type: native
    -
      heading: ''
      type: heading
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:13e8c0aa-c675-43d6-9443-8d93e3bd5b80' # Stadiums
      tableAttributes:
        - 'field:9c9fae53-56ca-49c0-b22c-a5301e981865' # Region
        - 'field:0123a4e4-2c99-4e36-b5cc-4dcb577b63a3' # Team
        - 'field:e990e909-8438-4c24-a235-6c086ae9edf6' # Badge
        - 'field:5878131a-7dba-477f-b0d6-902fa8722fda' # League
        - 'field:9828a3dc-019d-4e25-905d-4e2f7046d88b' # Team Colour
      type: native
    -
      heading: Structures
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:324611ef-56d7-4b2d-bdbd-aad65b3c18fb' # Navigation
      tableAttributes:
        - 'field:f390dfe0-620d-4ba5-8938-82816e24f438' # Icon
        - 'field:1d433b2b-0b4f-4503-8398-8eccef758024' # Navigation Link
      type: native
    -
      key: 'section:c044d02d-94fc-4b3a-8da7-e7a82a5963f3' # Pages
      type: native
email:
  fromEmail: sean_drury@hotmail.co.uk
  fromName: myfootballtour.co.uk
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: $IMAGES_PATH
    type: craft\fs\Local
    url: $ASSETS_BASE_URL
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: $TRANSFORM_PATH
    type: craft\fs\Local
    url: $ASSETS_BASE_URL
meta:
  __names__:
    1d433b2b-0b4f-4503-8398-8eccef758024: 'Navigation Link' # Navigation Link
    1e16db7a-6624-4b1c-a710-26613a5064e9: Images # Images
    2d2d4070-f3c3-43a0-b855-671dae34ab15: Home # Home
    2e9843eb-00f5-4a5a-8841-362d367feadd: 'Social Share' # Social Share
    02f114bd-d885-4d9d-9d23-b33fc220000e: 'Meta Description' # Meta Description
    3af9253e-53bd-40da-b9ff-f7ab98a669f3: Capacity # Capacity
    4a316ab3-49ff-4925-aada-2e783ce740ae: myfootballtour.co.uk # myfootballtour.co.uk
    4b7d6748-f9e7-4f63-9d59-25f3f3fb8cfb: 'Stadiums Home' # Stadiums Home
    6b146246-521b-46a8-a283-c6bc97088480: 'Default images' # Default images
    6c8c42c3-05c3-459d-8541-0e851ec675ac: Stadiums # Stadiums
    6dfa1059-e895-490e-8a03-b286ac3f1bc1: Default # Default
    07b10073-b192-44fb-ba57-71b3198ea2e0: Common # Common
    7c14063f-7d74-488c-bd7c-115425b4439f: Default # Default
    7f8641d9-b724-4273-9310-c2ffe0b4934c: Colour # Colour
    8d3403d7-8b7e-40af-abca-e33fd8a369fa: Left # Left
    9c9fae53-56ca-49c0-b22c-a5301e981865: Region # Region
    9fec835e-6354-48be-a311-ef98bd2ec6a8: Top # Top
    13e8c0aa-c675-43d6-9443-8d93e3bd5b80: Stadiums # Stadiums
    16b4ecbb-1c20-4583-b6bb-ea5ca8c3c576: Contact # Contact
    34a92e62-c13b-4922-aab2-db3e72a0d14e: 'Stadiums Home' # Stadiums Home
    69bafa99-be37-49ec-a361-4ba06906c386: Simple # Simple
    80bcbdd9-48fe-43df-98b6-e819bef2c02c: 'Google Maps' # Google Maps
    87ba3899-10a7-42c3-862f-eefec96e9753: 'Map image' # Map image
    92ff8290-8a29-43bf-9c83-024d958c06e7: Navigation # Navigation
    0123a4e4-2c99-4e36-b5cc-4dcb577b63a3: Team # Team
    228a5106-64d8-456d-8950-6617735b6a9e: Heading # Heading
    985f822c-337b-406b-b800-dfb08fd1513a: 'Main stadium image' # Main stadium image
    1922ec36-25bb-4e13-aeb9-c460fb1cb07f: myfootballtour.co.uk # myfootballtour.co.uk
    5902e87a-39bc-4bf3-ad43-44c38f9f1368: Meta # Meta
    7223d5fa-757c-4af3-aeb3-13ac25f9ca94: Default # Default
    9828a3dc-019d-4e25-905d-4e2f7046d88b: 'Team Colour' # Team Colour
    22551e37-4303-4127-9d5b-d5ae046c6f61: Body # Body
    324611ef-56d7-4b2d-bdbd-aad65b3c18fb: Navigation # Navigation
    654927ee-6ba5-4bad-8173-01b520580d6b: Opened # Opened
    5878131a-7dba-477f-b0d6-902fa8722fda: League # League
    aa2bd121-7363-4b83-ba39-5ab043f95b1b: Wikipedia # Wikipedia
    aad8776b-64a8-4298-925c-f7e998de33f9: Closing # Closing
    aaec7dbc-0bbb-4b12-9947-4b02335e61b7: 'Meta Title' # Meta Title
    b1ba8641-37f0-479a-8bf4-202546e2f8f1: 'Club website' # Club website
    c00bb2ae-23ed-4ea3-9980-2bb84200e929: Regions # Regions
    c044d02d-94fc-4b3a-8da7-e7a82a5963f3: Pages # Pages
    c570e08f-a17f-43b1-bf34-a61b09e2ca67: 'Club crest' # Club crest
    ccd834ae-2f70-46bd-a1cd-677ef90b6e7b: Home # Home
    df5f09a9-5651-4bd4-944f-e53e022e1714: 'Public Schema' # Public Schema
    e990e909-8438-4c24-a235-6c086ae9edf6: Badge # Badge
    ea3899cc-7f6f-4358-a8b4-d8da24f2e4e0: Gallery # Gallery
    f1fc23f6-c460-4917-8b97-6a68453c8ef5: Globals # Globals
    f35f0f33-69b3-4589-b27c-2c5bef818cf5: Contact # Contact
    f390dfe0-620d-4ba5-8938-82816e24f438: Icon # Icon
    f418958e-7e07-4cd0-b5b3-d6f120b4eb84: 'Default Social Share' # Default Social Share
    fbf6d79a-ab27-43a9-b11d-83e6aca93740: 'Team Colours' # Team Colours
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  quick-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
