dateModified: 1720884749
email:
  fromEmail: sean_drury@hotmail.co.uk
  fromName: myfootballtour.co.uk
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4a316ab3-49ff-4925-aada-2e783ce740ae: myfootballtour.co.uk # myfootballtour.co.uk
    6dfa1059-e895-490e-8a03-b286ac3f1bc1: Default # Default
    07b10073-b192-44fb-ba57-71b3198ea2e0: Common # Common
    1922ec36-25bb-4e13-aeb9-c460fb1cb07f: myfootballtour.co.uk # myfootballtour.co.uk
    324611ef-56d7-4b2d-bdbd-aad65b3c18fb: Navigation # Navigation
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
